[2023-11-09T03:07:32.360+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.train_test_val_split manual__2023-11-09T03:07:30.401282+00:00 [queued]>
[2023-11-09T03:07:32.439+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.train_test_val_split manual__2023-11-09T03:07:30.401282+00:00 [queued]>
[2023-11-09T03:07:32.442+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T03:07:32.451+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T03:07:32.453+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T03:07:32.506+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): train_test_val_split> on 2023-11-09 03:07:30.401282+00:00
[2023-11-09T03:07:32.531+0000] {standard_task_runner.py:55} INFO - Started process 2327 to run task
[2023-11-09T03:07:32.563+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'early_sepsis_prediction', 'train_test_val_split', 'manual__2023-11-09T03:07:30.401282+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpo466yrwd']
[2023-11-09T03:07:32.577+0000] {standard_task_runner.py:83} INFO - Job 101: Subtask train_test_val_split
[2023-11-09T03:07:32.740+0000] {task_command.py:388} INFO - Running <TaskInstance: early_sepsis_prediction.train_test_val_split manual__2023-11-09T03:07:30.401282+00:00 [running]> on host 4460f47ac51f
[2023-11-09T03:07:32.893+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=early_sepsis_prediction
AIRFLOW_CTX_TASK_ID=train_test_val_split
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T03:07:30.401282+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-09T03:07:30.401282+00:00
[2023-11-09T03:07:32.895+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: train_test_val_split() missing 1 required positional argument: 'data'
[2023-11-09T03:07:32.908+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=early_sepsis_prediction, task_id=train_test_val_split, execution_date=20231109T030730, start_date=20231109T030732, end_date=20231109T030732
[2023-11-09T03:07:32.925+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 101 for task train_test_val_split (train_test_val_split() missing 1 required positional argument: 'data'; 2327)
[2023-11-09T03:07:32.979+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T03:07:33.007+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
